### ISSUE TITLE
Noob Question

### ISSUE THREAD

**Issue by d1b1** [hunterloftis/throng#15]
I have noticed that other solutions that use the cluster module appear to have to figure out how to handle the master vs secondary workers. Love how tight throng in its cluster definition. How does throng differ from other Thread/Worker Managers?

**Comment by hunterloftis** [comment]
Cluster managers are a dime a dozen in node; throng is solid and easy, but not particularly special. The two primary design goals for this library are:

1. Testing. Lots of roll-your-own solutions or even published modules don't have sufficient test breadth for things like signal handling and error recovery.
2. Simplicity. Ideally, a one-liner should give you the most common use (fork X workers and keep them alive). I especially dislike the complexity of some of the other solutions that require multiple files.
