### ISSUE TITLE
Messaging

### ISSUE THREAD

**Issue by Udik** [hunterloftis/throng#18]
Hi, what about the possibility to exchange messages between master and workers?

Maybe it would be possible to add a "msgHandler" function parameter to the options and to modify the fork function to:

```
function fork() {
    var worker;
    for (var i = 0; i < opts.workers; i++) {
      worker = cluster.fork();
      if (options.msgHandler)
            worker.on('message', options.msgHandler);
    }
  }
```

and then in the options:

```
throng({
  workers: 16,
  master: masterFunction,
  start: startFunction,
  msgHandler: function(msg) {
      if (msg.type == "...")
          ...
      .....
  }
});
```

**Comment by hunterloftis** [comment]
The focus of throng is simplicity for the most common use case (simple forking to maximize resource use). If your application needs to get into inter-process messaging, I'd recommend using one of the existing more complex clustering libraries.

**Comment by Udik** [comment]
Still, now it's a road with a dead end. If at any point in the future you need inter-process communication, you have to switch to a different library. I'd at least put a warning in the documentation (dead end roads usually have warnings).

**Comment by bengourley** [comment]
Even though you started a worker with throng, if you do `require('cluster')` you have access to all the lower-level cluster/worker stuff. Would that meet your needs?

**Comment by Udik** [comment]
Thank you @bengourley , yes it should! I assumed that you could only get a handle on the spawned worker processes at fork() invocation, instead I see that cluster keeps a list of the forked workers visible to the master. That should solve my problem (and allows me to get rid of my locally modified copy of throng :) ).
Thanks!

**Comment by bengourley** [comment]
Awesome. Glad I could help! Great module @hunterloftis 👍
