### ISSUE TITLE
SIGINT listener do not stop exiting node

### ISSUE THREAD

**Issue by nahody** [hunterloftis/throng#24]
As described at Node Documentation, node should prevent from exit, when listener is defined on SIGINT or/and SIGTERM.

> If one of these signals has a listener installed, its default behavior will be removed (Node.js will no longer exit).

https://nodejs.org/api/process.html#process_signal_events

Using your example and comment out the process.exit line, node will still exit the process. 
```
const throng = require('./lib/throng');

throng({
  workers: 4,
  master: startMaster,
  start: startWorker
});
 
// This will only be called once 
function startMaster() {
  console.log(`Started master`);
}
 
// This will be called four times 
function startMaster()(id) {
  console.log(`Started worker ${ id }`);
 
  process.on('SIGTERM', () => {
    console.log(`Worker ${ id } exiting...`);
    console.log('(cleanup would happen here)');
    //process.exit();
  });
} 
```
I'm using OS X 10.12.3, Node 7.7.3 and throng 4.0.0.
Starting the method startMaster() without throng, results in node described behavior. The process don't exit.

**Comment by moshen** [comment]
This is because your worker has no more timers/async activity to keep it running.  With nothing left to do, the process exits.  If you make a `setTimeout` in the worker for something like 30 seconds, it will stay running.

**Comment by hunterloftis** [comment]
Exactly!
