### ISSUE TITLE
Question: performance and concurrency === 1

### ISSUE THREAD

**Issue by iamdevonbutler** [hunterloftis/throng#26]
Would you see performance gains if cluster was only initiated when CPU cores > 1?

**Comment by moshen** [comment]
Basically this just gives you worker restart-on-failure if you only are using one worker.  With more than one worker you should see better performance.

**Comment by hunterloftis** [comment]
You might see stability gains, but likely not much in the way of performance gains. You'd need to test at various concurrency levels to know for sure, however.
