### ISSUE TITLE
ctrl + C doesn't always seem to work

### ISSUE THREAD

**Issue by matthewmueller** [hunterloftis/throng#3]
Haven't figured out exactly why yet, but it seems like there's a closed PR that aims to address it. I'm just wondering if you've ran into something similar.

I believe this is also affecting `node-dev` or `nodemon` from restarting as well.

What's weird is that it doesn't happen everytime, just sometimes.

**Comment by matthewmueller** [comment]
You know, I think it's related to our app, but would just appreciate some thoughts on if you know why this would be happening.

**Comment by hunterloftis** [comment]
Usually if Ctrl-C doesn't work, there's a process intercepting signals. It could be throng, although I haven't experienced that myself.

Is it possible to create a self-contained test that reproduces the behavior, even intermittently?

**Comment by matthewmueller** [comment]
Haven't run into this for a while, so I'm going to close. Thanks!
