### ISSUE TITLE
Typescript typing issue with latest version

### ISSUE THREAD

**Issue by marcospgp** [hunterloftis/throng#31]
![image](https://user-images.githubusercontent.com/3464445/77453354-0feca600-6def-11ea-80b0-44e11bf31ef8.png)

![image](https://user-images.githubusercontent.com/3464445/77453370-1713b400-6def-11ea-90c7-af61d33ab89a.png)

**Comment by edvardchen** [comment]
Seems that you are giving  `process.env.WEB_CONCURRENCY` the wrong type `{workers: throng.WorkerCount; lifetime: number;}`

**Comment by hunterloftis** [comment]
This library is in JavaScript and does not define TypeScript types. Are you looking for https://www.npmjs.com/package/@types/throng?
